---

- hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:
    - name: Install supervisor
      apt:
        name: supervisor
        state: latest

    - name: Make sure supervisord is registered with systemd
      systemd:
        name: supervisor
        enabled: yes
        masked: no

    - name: Install pip3
      apt:
        name: python3-pip
        state: latest

    - name: Install configparser
      pip:
        name: configparser

    - name: Install pyserial
      apt:
        name: python3-serial
        state: latest

    - name: Install tkinter
      apt:
        name: python3-tk
        state: latest

    - name: Install rabbitmq and pika
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - rabbitmq-server
        - python3-pika
      notify: start rabbitmq

    - name: Make sure rabbitmq is registered with systemd
      systemd:
        name: rabbitmq-server
        enabled: yes
        masked: no

    - name: Install logrotate
      apt:
        name: logrotate
        state: latest

    - name: Configure logrotate
      copy:
        src: etc/logrotate.d/mt500
        dest: /etc/logrotate.d/mt500
      tags: logrotate_config

    - name: Create directory for pymt500
      file:
        path: "/home/{{ user }}/Desktop/pymt500"
        state: directory

    - name: Place watchdog source
      copy:
        src: "root/watchdog.py"
        dest: "/root/watchdog.py"
      tags: watchdog

    - name: Create cron for watchdog
      copy:
        src: "etc/cron.d/mt500_watchdog"
        dest: "/etc/cron.d/mt500_watchdog"
      tags: watchdog_cron

    - name: Place pymt500 source
      copy:
        src: "iflows/Desktop/pymt500/{{ item }}"
        dest: "/home/{{ user }}/Desktop/pymt500/{{ item }}"
      with_items:
        - mt500.py
        - mt500_ui.py
        - purge_queues.py
      tags: mt500_source

    - name: Template pymt500 config
      template:
        src: iflows/Desktop/pymt500/mt500.conf
        dest: "/home/{{ user }}/Desktop/pymt500/mt500.conf"
      notify: restart supervisor
      tags: mt500_config

    - name: Create directory for log files
      file:
        path: /var/log/mt500
        state: directory

    - name: Create log files
      file:
        path: /var/log/mt500/{{ item }}
        state: touch
      with_items:
        - error.log
        - debug.log

    - name: Create python symlink
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link

    - name: Place supervisor config
      template:
        src: etc/supervisor/conf.d/mt500.conf
        dest: /etc/supervisor/conf.d/mt500.conf
      notify: restart supervisor

    - name: Place mt500 conf template
      copy:
        src: iflows/mt500.conf.j2
        dest: /home/{{ user }}/iflows/mt500.conf.j2

    - name: Place mt500 configuration script
      copy:
        src: usr/bin/configure_mt500
        dest: /usr/bin/configure_mt500
        mode: '0755'

    - name: Place meshcentral install script
      copy:
        src: iflows/install_meshcentral.sh
        dest: /home/{{ user }}/install_meshcentral.sh
        mode: '0755'

    - name: Install meshcentral agent
      shell:
        cmd: ./install_meshcentral.sh
        chdir: /home/{{ user }}

    - name: Enable desktop icons
      command: gsettings set org.gnome.desktop.background show-desktop-icons true

    - name: Restart mt500
      command: /bin/true
      notify: restart supervisor

    - name: Purge queues
      command: python3 /home/{{ user }}/Desktop/pymt500/purge_queues.py

  handlers:
    - name: restart supervisor
      service:
        name: supervisor
        state: restarted

    - name: start rabbitmq
      service:
        name: rabbitmq-server
        state: started
