---

- hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:
    - name: Install supervisor
      apt:
        name: supervisor
        state: latest

    - name: Install pyserial
      apt:
        name: python-serial
        state: latest

    - name: Install tkinter
      apt:
        name: python-tk
        state: latest

    - name: Install requests
      apt:
        name: python-requests
        state: latest

    - name: Install rabbitmq and pika
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - rabbitmq-server
        - python-pika
      notify: start rabbitmq

    - name: Install logrotate
      apt:
        name: logrotate
        state: latest

    - name: Configure logrotate
      copy:
        src: etc/logrotate.d/mt500
        dest: /etc/logrotate.d/mt500

    - name: Place watchdog source
      copy:
        src: "root/watchdog.py"
        dest: "/root/watchdog.py"
      tags: watchdog

    - name: Place supervisor monitor source
      copy:
        src: "root/supervisor_running.py"
        dest: "/root/supervisor_running.py"
      tags: watchdog

    - name: Create cron for watchdog
      copy:
        src: "etc/cron.d/mt500_watchdog"
        dest: "/etc/cron.d/mt500_watchdog"
      tags: watchdog

    - name: Create directory for pymt500
      file:
        path: "/home/{{ user }}/Desktop/pymt500"
        state: directory

    - name: Place pymt500 source
      copy:
        src: "iflows/Desktop/pymt500/{{ item }}"
        dest: "/home/{{ user }}/Desktop/pymt500/{{ item }}"
      with_items:
        - mt500.py
        - mt500_ui.py
        - purge_queues.py
      tags: mt500_source

    - name: Template pymt500 config
      template:
        src: iflows/Desktop/pymt500/mt500.conf
        dest: "/home/{{ user }}/Desktop/pymt500/mt500.conf"
      notify: restart supervisor
      tags: mt500_config

    - name: Create directory for log files
      file:
        path: /var/log/mt500
        state: directory

    - name: Create log files
      file:
        path: /var/log/mt500/{{ item }}
        state: touch
      with_items:
        - error.log
        - debug.log

    - name: Place supervisor config
      template:
        src: etc/supervisor/conf.d/mt500.conf
        dest: /etc/supervisor/conf.d/mt500.conf
      notify: restart supervisor

    - name: Enable desktop icons
      command: gsettings set org.gnome.desktop.background show-desktop-icons true 

    - name: Restart mt500
      command: /bin/true
      notify: restart supervisor

    - name: Purge queues
      command: python /home/{{ user }}/Desktop/pymt500/purge_queues.py
      tags: purge_queues

  handlers:
    - name: restart supervisor
      service:
        name: supervisor
        state: restarted

    - name: start rabbitmq
      service:
        name: rabbitmq-server
        state: started
